### ISSUE TITLE
Start decoupling `helm-controller` from resulting PromFed binary

### ISSUE THREAD

**Issue by mallardduck** [rancher/prometheus-federator#148]
Per title, this issue/RFE is simply for our team to consider the potential for fully removing the embedded helm-controller.

# Summary

The primary objective of this effort would be to decouple the `helm-controller` from the PromFed binary. In turn directly reducing the complexity of delivering a PromFed that is compatible with all target distros (rke2/k3s, cloud, etc) and varying k8s versions.

The PromFed project and chart would still depend on `helm-controller` but instead of building into the binary would consume the original image. This will de-duplicate redundant efforts across projects and helm-controller systems within a cluster.

Finally, once the PromFed binary built in version is ready for removal it will simplify the PromFed project further by allowing us to remove the complicated `helm-controller` crd management we've needed to fix other bugs on k3s/rke2 systems.

# Solution

## Remove `helm-controller` as a godep for PromFed, make it a sibling container instead

This option entails keeping the existing functionality we surface to PromFed users today with a different implementation  at a k8s level.Instead of a true "embedded" controller in PromFed binary, it would become a new `helm-controller` pod or deployment.  The goal would be a compatible end-user experience with new opt-in helm fields to use the new mechanism. 

The end result is still "embedded" - in the experience of using the chart - but not statically at compile time.

While this option has some considerable cons (see [original issue text](https://github.com/rancher/prometheus-federator/issues/148#issuecomment-3429898345)) - the Pros greatly outweigh those risks. We can mitigate most of those risks by creating good documentation - both formal docs, release notes and helm-chart docs (in `values.yaml`).

### Background

3 Simple Supported Config Setups:
- A) **PromFed** is the _only_ possible `helm-controller` on Cluster:
  - The `helm-controller` w/ PromFed must be used (will now be a pod).
- B)**PromFed** is on _Cluster with existing Global_ `helm-controller`:
  - Cannot have PromFed's `helm-controller` enabled.
  - Based on talking with @brandond, mixing global and namespace scoped helm-controller instances is not fully supported.
    - It may work but also may have weirdness - if it needs to be supported Team ORBS can work in k3s upstream for `helm-controller` to add support properly.
- C) **PromFed** is on a _Cluster with Namespace scoped controller_ instances:
  - User's can either: a) deploy one for PromFed like their existing `helm-controller` instances, or b) use the PromFed one setting the `values.yaml` to match the `helm-controller` version.

Important Context:
- `helm-controller` supports either: a single global controller watching every NS, or many NS scoped instances.
- `helm-controller` doesn't support a mixture of both of these modes in the same cluster.
- Today's PromFed integration for helm-controller leads to conflicts easily even on a single Rancher Minor version, because:
  - The existing PromFed embedded `helm-controller` is always locked at a single version (at build time).
  - k3s/RKE2 will update `helm-controller` versions on patch releases.
  - This can lead to CRD version conflicts and other weird issues
- The existing PromFed embedded `helm-controller` both:
  - Installs under a new name, and
  - Installs under a namespace, so becomes namespace scoped.
- Technically, the `ManagedBy` annotation that `helm-controller` supports does allow multiple controller instances to have overlapping namespace scopes w/o conflict via Alternative names.
  -  In other words, mixing global and namespaced ones works with specific steps taken - as that's partially how PromFed can co-exist with global ones with proper configs.
  - The lease mechanism will allow both: global and/or many ns-scoped instances to hold a lease.
    - Using both together isn't officially supported, as mentioned above, but technically possible as long as each NS specific instance has a custom `ControllerName` set to differentiate `ManagedBy` and ensure global instance won't touch the ones for NS-scoped controllers.
    - The current `helm-controller` lease mechanism will **not** allow locks for: multiple global instances, or multiple ns-scoped instances within the same ns. (In this case, a second Global instance lock will overlap with the first and similarly any additional ns-scoped in the same NS overlap.)

### The 1 Secret Unsupported Config:

This option is specific to k3s/RKE2 clusters only. We will call it B.2 - because it's option B, but we keep the new "external but embedded" `helm-controller` enabled.

It is technically not officially supported or consider supported by k3s upstream `helm-controller` project. As such it may not need to be tested, but because it is possible I wanted to document it here. The configuration is rather easy but does take an additional step and extra attention to detail - this is another reason why the documented option B is preferred to this route.

#### How?
1. Identify the version of k3s/RKE2 in use,
2. Pull up the release notes for that k8s minor version of k3s/RKE2,
3. Find the specific version in the table and make note of the `helm-controller` columns value,
4. During PromFed install set the `.Values.helmController.deployment.image.tag` value to match,
5. Also follow other "normal testing steps" for this new mode,
6. Observe the new PromFed deployment/pod for `helm-controller` that should use the version you set.

Example: Assume we are using RKE2 `v1.33.5+rke2r1` we would look at [Release Notes](https://docs.rke2.io/release-notes/v1.33.X) and find that version uses `helm-controller` of version `v0.16.13`. That is the version we would set for `.Values.helmController.deployment.image.tag`. In the future, if upgrading the k8s version of the cluster would change the distro built-in controller version, then an update for the PromFed helm release should be done to match.

**Comment by diogoasouza** [comment]
The [PR](https://github.com/rancher/prometheus-federator/pull/271) is working as expected and is ready for review. However, this is marked as a feature and we are past the feature complete date, so the milestone will need to be updated.

cc @prachidamle

**Comment by prachidamle** [comment]
In the light of the above analysis, moving to v2.14.0

**Comment by mallardduck** [comment]
Can be tested with charts from: https://github.com/rancher/charts/pull/6864

**Comment by pankajsqe** [comment]
Test Pass : Verified decoupling of helm controller from  prometheus-federator binary. Also `.Values.helmController.deployment.image.tag `are populating as per kubernetes version from release note.


Details:
Rancher : `V2.14.0-alpha7`
Cluster : `v1.33.1+rke2r1`
Helm-controller : [v0.16.10](https://github.com/k3s-io/helm-controller/releases/tag/v0.16.10) From Release Note
Rancher-monitoring:`109.0.0-rc.2+up80.9.1-rancher.4`
Prometheus-federator:1`09.0.0-rc.1+up6.0.0-alpha.2`

<img width="991" height="141" alt="Image" src="https://github.com/user-attachments/assets/65fedb7e-46e7-4e10-85ff-f1cf1b334745" />



**Scenario 1 - Default Values**
```
root@ip-:/home/ubuntu# helm get values prometheus-federator -n cattle-monitoring-system
USER-SUPPLIED VALUES:
global:
  cattle:
    clusterId: local
    clusterName: local
    rkePathPrefix: ""
    rkeWindowsPathPrefix: ""
    systemDefaultRegistry: ""
    systemProjectId: p-wvzkd
    url: https://rancher.3.14.6.117.sslip.io
  systemDefaultRegistry: ""

root@ip-:/home/ubuntu# kubectl get helmcharts -n cattle-monitoring-system   cattle-project-p-hphbp-monitoring -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,CHART_URL:.metadata.annotations.helm\\.cattle\\.io/chart-url,MANAGED_BY:.metadata.annotations.helmcharts\\.cattle\\.io/managed-by
NAMESPACE                  NAME                                CHART_URL   MANAGED_BY
cattle-monitoring-system   cattle-project-p-hphbp-monitoring   <none>      prometheus-federator
```

<img width="1728" height="217" alt="Image" src="https://github.com/user-attachments/assets/bcd3772b-edd2-494c-a6dd-73ee2b48c0e9" />
-------------------------------------------------------------------------------------------------------------


**Scenario 2 : Both helmController with false values**
```
root@ip-:/home/ubuntu# helm get values prometheus-federator -n cattle-monitoring-system
USER-SUPPLIED VALUES:
global:
  cattle:
    clusterId: local
    clusterName: local
    rkePathPrefix: ""
    rkeWindowsPathPrefix: ""
    systemDefaultRegistry: ""
    systemProjectId: p-wvzkd
    url: https://rancher.3.14.6.117.sslip.io
  systemDefaultRegistry: ""
helmProjectOperator:
  helmController:
    enabled: false

root@ip-:/home/ubuntu# kubectl get helmcharts -n cattle-monitoring-system   cattle-project-p-hphbp-monitoring -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,CHART_URL:.metadata.annotations.helm\\.cattle\\.io/chart-url,MANAGED_BY:.metadata.annotations.helmcharts\\.cattle\\.io/managed-by
NAMESPACE                  NAME                                CHART_URL   MANAGED_BY
cattle-monitoring-system   cattle-project-p-hphbp-monitoring   <none>      helm-controller
```

<img width="1728" height="254" alt="Image" src="https://github.com/user-attachments/assets/03140ee5-d4cf-4540-ac81-3137c08876d8" />

------------------------------------------------------------------------------------------------------------

**Scenario 3 : Both helmController with false values and externalHelmControllerName**
```
root@ip:/home/ubuntu# helm get values prometheus-federator -n cattle-monitoring-system
USER-SUPPLIED VALUES:
externalHelmControllerName: pkumar-test-helm-controller
global:
  cattle:
    clusterId: local
    clusterName: local
    rkePathPrefix: ""
    rkeWindowsPathPrefix: ""
    systemDefaultRegistry: ""
    systemProjectId: p-wvzkd
    url: https://rancher.3.14.6.117.sslip.io
  systemDefaultRegistry: ""
helmProjectOperator:
  helmController:
    enabled: false
root@ip:/home/ubuntu# kubectl get helmcharts -n cattle-monitoring-system   cattle-project-p-hphbp-monitoring -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,CHART_URL:.metadata.annotations.helm\\.cattle\\.io/chart-url,MANAGED_BY:.metadata.annotations.helmcharts\\.cattle\\.io/managed-by
NAMESPACE                  NAME                                CHART_URL   MANAGED_BY
cattle-monitoring-system   cattle-project-p-hphbp-monitoring   <none>      "pkumar-test-helm-controller"
```

<img width="1727" height="278" alt="Image" src="https://github.com/user-attachments/assets/8c38688a-0e35-404a-be8f-51b34b582e81" />



*Scenario 4 : helmController.deployment.enabled= true and helmProjectOperator.helmController.enabled=false**


helmController:
  deployment:
    enabled: true
    image:
      pullPolicy: IfNotPresent
      repository: rancher/helm-controller
      tag: v0.16.10
    replicas: 1

helmProjectOperator:
  helmController:
    enabled: false
    job:
      image:
        repository: rancher/klipper-helm
        tag: v0.9.4-build20250113

<img width="1219" height="766" alt="Image" src="https://github.com/user-attachments/assets/6dc80ef0-a788-4dd7-9f5a-3ec280a61c87" />
<img width="1220" height="654" alt="Image" src="https://github.com/user-attachments/assets/1e1666cc-9cc1-40b5-a11e-76c8ea34d814" />

cc: @diogoasouza, @mallardduck
