### ISSUE TITLE
Project Owner permission error when viewing Grafana dashboards via proxy

### ISSUE THREAD

**Issue by puffitos** [rancher/prometheus-federator#46]
**Cluster Setup**
- Kubernetes version: v1.20.15
- Type of Cluster: RKE1
- Installation option (Helm Chart):
 ```yaml
global:
  cattle:
    clusterId: c-kpg24
    clusterName: t21
    rkePathPrefix: ""
    rkeWindowsPathPrefix: ""
    systemDefaultRegistry: mtr.devops.telekom.de
    systemProjectId: p-6gndd
    url: https://*****.de
  systemDefaultRegistry: mtr.devops.telekom.de
helmProjectOperator:
  projectReleaseNamespaces:
    labelValue: cattle-monitoring
  releaseRoleBindings:
    clusterRoleRefs:
      admin: admin
      edit: edit
      view: view   
```
**Describe the bug**
If a project owner activates Project Monitoring (monitoring v2), and they are not a Cluster Owner, they get the following error, when viewing a Grafana Dashboard (via the proxy URL):
```
Error services "http:cattle-project-p-t9zwm-monitoring-grafana:80" is forbidden: User "u-umctamlw5n" cannot create resource "services/proxy" in API group "" in the namespace "cattle-project-p-t9zwm-monitoring"
```

The role cattle-project-p-t9zwm-mon-admin is missing this Permission as well:

```yaml
rules:
  - apiGroups:
  - ""
resourceNames:
  - http:cattle-project-p-t9zwm-mon-prometheus:9090
  - https:cattle-project-p-t9zwm-mon-prometheus:9090
  - http:cattle-project-p-t9zwm-mon-alertmanager:9093
  - https:cattle-project-p-t9zwm-mon-alertmanager:9093
  - http:cattle-project-p-t9zwm-monitoring-grafana:80
  - https:cattle-project-p-t9zwm-monitoring-grafana:80
resources:
  - services/proxy
verbs:
  - get
```

A Cluster Owner doesn't get the error mentioned, I guess some other role allows them to create the services/proxy resource.

**To Reproduce**

1. Install prometheus operator
2. Activate Project Monitoring with standard values
3. Visit the grafana dashboard, wait a few secs.

**Result**

The error message appears in grafana. The function of the prometheus stack doesn't seem affected by this.

**Expected Result**

No error regarding proxy connections should appear.

**Screenshots**
https://imgur.com/FbAfUuz

**Additional context**
None
