### ISSUE TITLE
[project-monitoring] Ingress upgrade failed due the missing ownership resource

### ISSUE THREAD

**Issue by eumel8** [rancher/prometheus-federator#53]
**Describe the bug**

We have a project monitoring with exposed Ingress for Prometheus:

```yaml
apiVersion: helm.cattle.io/v1alpha1
kind: ProjectHelmChart
spec:
  values:
    prometheus:
      ingress:
        enabled: true
        hosts:
        - xxxx
        paths:
        - /
```

First installation is fine, Ingress works and is reachable. But the next upgrade of the Helm chart failed:

```
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: Ingress "cattle-project-p-h4xn2-mon-prometheus" in namespace "cattle-project-p-h4xn2-monitoring" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "cattle-project-p-h4xn2-monitoring"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "cattle-project-p-h4xn2-monitoring"

```

The Ingress has the following metadata:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/publicEndpoints: xxx
    objectset.rio.cattle.io/id: object-set-applier
    objectset.rio.cattle.io/owner-gvk: internal.cattle.io/v1alpha1, Kind=objectSetState
    objectset.rio.cattle.io/owner-name: cattle-project-p-h4xn2-monitoring
    objectset.rio.cattle.io/owner-namespace: cattle-project-p-h4xn2-monitoring
  creationTimestamp: "2023-02-13T21:38:21Z"
  generation: 1
  labels:
    app: rancher-project-monitoring-prometheus
    app.kubernetes.io/instance: cattle-project-p-h4xn2-monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: rancher-project-monitoring
    app.kubernetes.io/version: 0.2.0
    chart: rancher-project-monitoring-0.2.0
    heritage: Helm
    objectset.rio.cattle.io/hash: xxxx
    release: cattle-project-p-h4xn2-monitoring
  name: cattle-project-p-h4xn2-mon-prometheus
  namespace: cattle-project-p-h4xn2-monitoring
```

**To Reproduce**

Install project monitoring with Ingress config

**Result**

see above

**Expected Result**
installation is upgradable

**Additional context**

Not sure if this comes from the chart itself or the [Helm Project Operator](https://github.com/rancher/helm-project-operator)
