### ISSUE TITLE
Project Registration Namespaces are NOT imported into correspondent Projects when deploying prometheus-federator with fleet 

### ISSUE THREAD

**Issue by Labidi-github** [rancher/prometheus-federator#9]
**Cluster Setup**
- Kubernetes version: 
- Type of Cluster (RKE1, RKE2, k3s, EKS, GKE, AKS, OKE, etc): EKS
- Installation option (Helm Chart / Custom Installation):
   - If Helm Chart, did you supply any non-default values? If so, what values did you supply: default values
   - If Custom Installation, how did you install it (kustomize, k8s manifest, etc.):
   
**Describe the bug**
When installing prometheus-federator with fleet, keeping default helm chart values, Project Registration Namespaces (cattle-project-id) are NOT imported into the Project it is tied to. Therefore, project-owners can't create "Project Monitors" in the Rancher UI. Solution becomes in-exploitable!

**To Reproduce**
fleet.yaml file:
```
defaultNamespace: cattle-monitoring-system
helm:
  releaseName: prometheus-federator
  repo: https://charts.rancher.io
  chart: prometheus-federator
  version: 0.1.0
```

**Result**
"cattle-project-id"    NOT in project

**Expected Result**
"cattle-project-id"   shoud be imported in the project  "project-id"

**Screenshots**

**Additional context**

**Comment by Labidi-github** [comment]
The only way found to deploy correctly prometheus-federator is to not use default values ! 
"clusterId", "systemProjectId" and "url" should be fixed in fleet.yaml file. exp:
fleet.yaml file:
```
defaultNamespace: cattle-monitoring-system
helm:
  releaseName: prometheus-federator
  repo: https://charts.rancher.io
  chart: prometheus-federator
  version: 0.1.0
  values: 
    global:
      cattle:
        clusterId: global.fleet.clusterLabels.management.cattle.io/cluster-name 
        clusterName: global.fleet.clusterLabels.management.cattle.io/cluster-display-name
        systemProjectId: p-ft5v6
        url: https://my.local.cluster.url.com
```

How can we avoid hard coding "systemProjectId" and "url" values ?
